project:
  type: website
  output-dir: docs

website:
  title: "Data management and statistical analysis plans"
  sidebar:
    style: "docked"
    search: true
    repo-url: https://github.com/tjuheide/DataManagementSAP
    contents:
      - href: index.qmd
        text: Home
        contents: 
        - basics.qmd
      - section: "Pharmacoepidemiology"
        href: pe.qmd
        contents: 
        - nuac.qmd

format:
  html:
    toc: true
    html-table-processing: none
    theme:
      - united



